language: rust

cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - rustup component add rust-src
  - rustup target add thumbv7m-none-eabi

script:
  - cargo build
  - cargo test
  - cd no-std-example && cargo build
