language: rust

cache: cargo
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - qemu
      - qemu-system-arm

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
  - TARGET=aarch64-unknown-linux-gnu
  - TARGET=arm-unknown-linux-gnueabi
  - TARGET=armv7-unknown-linux-gnueabihf
  - TARGET=thumbv7em-none-eabihf

install:
  - rustup component add rust-src
  - rustup target add $TARGET

script:
  - cargo build --verbose --target $TARGET --no-default-features 
  - cargo test --target thumbv7m-linux-eabi --no-run
  - qemu-arm target/thumbv7m-linux-eabi/debug/mos6502