language: rust

rust:
  - stable
  - beta
  - nightly

allow_failures:
  - rust: nightly
fast_finish: true

env:
  - TARGET=aarch64-unknown-linux-gnu
  - TARGET=arm-unknown-linux-gnueabi
  - TARGET=armv7-unknown-linux-gnueabihf
  - TARGET=thumbv7em-none-eabihf

install:
  - rustup component add rust-src
  - rustup target add $TARGET

script:
  - cargo build --target $TARGET
  - cargo test --target $TARGET