language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=thumbv7em-none-eabihf
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - rustup component add rust-src
  - rustup target add $TARGET

script:
  - cargo build --target $TARGET
  - cargo test --target $TARGET