language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - pushd /
  - rustup component add rust-src
  - rustup target add thumbv7em-none-eabihf
  - popd