language: rust

cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
  - TARGET=aarch64-unknown-linux-gnu
  - TARGET=arm-unknown-linux-gnueabi
  - TARGET=armv7-unknown-linux-gnueabihf
  - TARGET=thumbv7em-none-eabihf

install:
  - rustup component add rust-src
  - rustup target add $TARGET

script:
  - cargo build --verbose --target $TARGET --no-default-features 
  - cargo test --verbose --target $TARGET --no-default-features 